language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: szeyick-github
    token:
      secure: Hc6XEtMyk0DIFPtYeHwCH7Q84lxOAyWNu2Nt1cqH6K6B7E+lbqdVG1x62FLy+eQlREW+IRLpQILLjtTAfZ+lYfr4jqyeXygfID9s2eCvM0MGOsWOIX/EN8/lkCJkVd43BL5FhCS577HLvmaQsc4hninFyDMEOfeYikJAGi7JCtc/LSBBFoWQD45ZWAVCTr1jplSr2GNwWEtZWgwn0FL4HyyJdmZ7lCtiV5rr1Yzml8cRiWtALOaRWhwnsLbdnw4OrdAGOFFtS5qpQ9WtdEqpfPvILxwket4qC4OoFM/OMDS3sdM2qe1D0tnWf0MwbQGfZNwaVH778w0f0t5abI6Sb/z6BkgExhDh3kMNhczh4p3/AOTWZgUEnMJJHaBA4zMTln32y0olQg4AcLxz20uJtqtP2KZLfWc3HrHBHWpru+5jCuWrhkukwVdNzdq8d1QyPBxyynilTOcQSB4TCHHb+5oa1Yo5e3SYBwr76M1cMXPAINjH0QMCR/UfX9TUUgND9VO+M4hp0/XzYHoIjjaFqbHt4vUcs2L0wAmtJGqKRTkAzsyFPjJXgPu8DGoYJTWY5CBzK4AkN+WIZRcRZoHSXCBYy+MudP/EN8XXHAqLTjYXJD4vyallW6eoYvRbvHMZEa5novAm0ut5ZVo6iBMPm2e6D3Zfz7Ga9zqlMKW3t8Y=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
